### ISSUE TITLE
希望建立联系

### ISSUE THREAD

**Issue by TrumanDu** [ZTO-Express/zms#2]
你好，看到你们开源的消息平台，做的很好，我们也有开源kafka平台[KafkaCenter](https://github.com/xaecbd/KafkaCenter) ,didi 消息开源团队我们也有联系，**希望我们可以建立联系**，做更好的消息平台，做好开源事业。

如果可以的话，可以留个联系方式。

**Comment by ZTOGroup** [comment]
> 你好，看到你们开源的消息平台，做的很好，我们也有开源kafka平台[KafkaCenter](https://github.com/xaecbd/KafkaCenter) ,didi 消息开源团队我们也有联系，**希望我们可以建立联系**，做更好的消息平台，做好开源事业。
> 
> 如果可以的话，可以留个联系方式。

可以的，直接把微信或钉钉 发给 xiaowenke@zto.com或者dingwei0336@zto.com 我们加你

**Comment by TrumanDu** [comment]
已发邮件。
